### ISSUE TITLE
populate properties in api results with default values

### ISSUE THREAD

**Issue by FragsterAt** [zerobias/telegram-mtproto#12]
when api returned object with default values (empty string, zero etc) in properties, objects, returned with callApi hasn't this properties. This make results unusable in next calls without additional manipulations.
for example client.callApi('auth.signIn', args) has result.user (for me):
```
   anonymous {
     _writeBuffers: null,
....
     mutual_contact: true,
     id: 8....8,
     access_hash: '0xf....f',
     first_name: 'Anton',
// here must be last_name and username, see https://core.telegram.org/constructor/userSelf
     phone: '7...9',
     photo: ...
...
```

initial project (https://github.com/goodmind/telegram-mt-node) has this properties populated.

**Comment by goodmind** [comment]
Should be fixed in https://github.com/zerobias/telegram-mtproto/pull/13/commits/1033b2574f9194ba003eca9c0f3e151e03ce525b

**Comment by FragsterAt** [comment]
@goodmind, I am doing something wrong?

> npm update
> shedsender@0.1.0 /home/antonio/work/
> └── telegram-mtproto@1.1.0  (git+https://github.com/zerobias/telegram-mtproto.git#c5815111a930a812f4e53438e209f481365138b8)

but issue still exists

**Comment by goodmind** [comment]
@FragsterAt Maybe you just don't have last name? 😬

**Comment by FragsterAt** [comment]
@goodmind you can compare output of auth.signIn https://github.com/goodmind/telegram-mt-node and https://github.com/zerobias/telegram-mtproto if you have blank username or last name

**Comment by FragsterAt** [comment]
it can be seen with client.callApi('messages.getDialogs',...).then(result => result.chats.list) and false values for admin, admins_enabled, creator etc.

**Comment by goodmind** [comment]
@FragsterAt this is intended behavior, are you sure that you are using https://github.com/goodmind/telegram-tl-node ?

**Comment by FragsterAt** [comment]
@goodmind at start, i'm using "npm install telegram.link". 
last week i'm succesfully migrate to "git+https://github.com/zerobias/telegram-mtproto.git" (it much better, thanks, guys!), but in some places, where I put the call results to the database directly, I started getting errors about a null value in the columns, that do not allow null. ImportContacts, SignIn, etc...

**Comment by goodmind** [comment]
@FragsterAt properties which are `flags` can be undefined:
Take a look at schema:
https://github.com/zerobias/telegram-mtproto/blob/mtproto2/schema/api-57.json#L3413

**Comment by FragsterAt** [comment]
@goodmind thanks for description!
